export const FETCH_CHARACTERS = "FETCH_CHARACTERS";
export const FETCH_CHARACTER_PROFILE = "FETCH_CHARACTER_PROFILE";
export const SELECT_CHARACTER = "SELECT_CHARACTER";
export const FETCH_CHARACTER_MOVIES = "FETCH_CHARACTER_MOVIES";
